# Generated by Django 2.2.6 on 2019-10-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('commments', models.TextField()),
            ],
        ),
    ]
