# Generated by Django 2.2.6 on 2019-10-20 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name_plural': 'Contact'},
        ),
        migrations.RenameField(
            model_name='contactmodel',
            old_name='commments',
            new_name='comments',
        ),
    ]
